name: gdal
channels:
  - defaults
  - conda-forge
dependencies:
  - gdal
  - geopandas
  - numpy
  - pandas
  - pyarrow
  - python
  - rasterio
  - scikit-learn
  - shapely
  - xarray
variables:
  USE_PATH_FOR_GDAL_PYTHON: YES

