name: gdal
channels:
  - conda-forge
  - conda-forge
dependencies:
  - gdal=3.2.2
  - numpy=1.21.6
  - psutil
  - pyarrow
  - python=3.7.12
  - fiona=1.8.19
  - pip:
      - geopandas
      - pandas
      - shapely
