name: Test All Functions

on:
  [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Test New Code Outputs vs Old Outputs
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0} # For conda envs: https://github.com/marketplace/actions/setup-miniconda#important

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7  # Replace with your desired Python version
    
    - name: Download GDAL and Python installers
      run: |
        curl -o python-3.7.9-amd64.exe https://www.python.org/ftp/python/3.7.9/python-3.7.9-amd64.exe
        curl -o gdal-301-1900-x64-core.msi http://download.gisinternals.com/sdk/downloads/release-1900-x64-gdal-3-1-3-mapserver-7-6-1/gdal-301-1900-x64-core.msi
    
    - name: Install GDAL
      run: |
        python-3.7.9-amd64.exe InstallAllUsers=1 Include_test=0
        msiexec /i gdal-301-1900-x64-core.msi
    
    - name: Add GDAL and Python to PATH
      run: |
        echo "C:\Program Files\GDAL" >> $GITHUB_PATH
        echo "C:\Python37" >> $GITHUB_PATH
        echo "C:\Python37\Scripts" >> $GITHUB_PATH
        
    - name: Set GDAL_DATA and GDAL_DRIVER_PATH
      run: |
        echo "GDAL_DATA=C:\Program Files\GDAL\gdal-data" >> $GITHUB_ENV
        echo "GDAL_DRIVER_PATH=C:\Program Files\GDAL\gdalplugins" >> $GITHUB_ENV
        
    - name: Check environment variables
      run: |
        echo "GDAL_DATA: $GDAL_DATA"
        echo "GDAL_DRIVER_PATH: $GDAL_DRIVER_PATH"
        
    - name: Run your script
      run: |
        python tests/test_funcs.py  # Replace with the actual path to your test script