name: Test All Functions

on:
  [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Test New Code Outputs vs Old Outputs
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0} # For conda envs: https://github.com/marketplace/actions/setup-miniconda#important

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace with your desired Python version
    
    - name: Install GDAL dependencies
      run: |
        # Download GDAL and Python installers
        Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.7.9/python-3.7.9-amd64.exe" -OutFile "python-3.7.9-amd64.exe"
        Invoke-WebRequest -Uri "http://download.gisinternals.com/sdk/downloads/release-1900-x64-gdal-3-1-3-mapserver-7-6-1/gdal-301-1900-x64-core.msi" -OutFile "gdal-301-1900-x64-core.msi"
        
        # Install GDAL
        Start-Process -Wait -FilePath "python-3.7.9-amd64.exe" -ArgumentList "/quiet InstallAllUsers=1 Include_test=0"
        Start-Process -Wait -FilePath "gdal-301-1900-x64-core.msi" -ArgumentList "/quiet"
        
        # Add GDAL and Python to PATH
        [Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Program Files\GDAL;C:\Python37;C:\Python37\Scripts", [EnvironmentVariableTarget]::Machine)
    
    - name: Set GDAL_DATA and GDAL_DRIVER_PATH
      run: |
        [Environment]::SetEnvironmentVariable("GDAL_DATA", "C:\Program Files\GDAL\gdal-data", [EnvironmentVariableTarget]::Machine)
        [Environment]::SetEnvironmentVariable("GDAL_DRIVER_PATH", "C:\Program Files\GDAL\gdalplugins", [EnvironmentVariableTarget]::Machine)
        
    - name: Check environment variables
      run: |
        echo "GDAL_DATA: $env:GDAL_DATA"
        echo "GDAL_DRIVER_PATH: $env:GDAL_DRIVER_PATH"
        
    - name: Run your script
      run: |
        python tests/test_funcs.py  # Replace with the actual path to your test script